version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BLOCKCHAIN_RPC_URL=${BLOCKCHAIN_RPC_URL}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    restart: unless-stopped
    networks:
      - cripplefn-network
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - cripplefn-network
    depends_on:
      - backend

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - cripplefn-network
    volumes:
      - redis_data:/data

networks:
  cripplefn-network:
    driver: bridge

volumes:
  backend_data:
  redis_data:
